<?php
/**
 * CreateRegistrationRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Maximum.CRM.WebApps.CommonIntegration
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateRegistrationRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Запрос на создание/обновление регистрации
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateRegistrationRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateRegistrationRequest"
     */
    public function testCreateRegistrationRequest()
    {
    }

    /**
     * Test attribute "first_parent"
     */
    public function testPropertyFirstParent()
    {
    }

    /**
     * Test attribute "second_parent"
     */
    public function testPropertySecondParent()
    {
    }

    /**
     * Test attribute "schoolchild"
     */
    public function testPropertySchoolchild()
    {
    }

    /**
     * Test attribute "product_code"
     */
    public function testPropertyProductCode()
    {
    }

    /**
     * Test attribute "event_code"
     */
    public function testPropertyEventCode()
    {
    }

    /**
     * Test attribute "campaign_code"
     */
    public function testPropertyCampaignCode()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "territory_code"
     */
    public function testPropertyTerritoryCode()
    {
    }

    /**
     * Test attribute "issue_year"
     */
    public function testPropertyIssueYear()
    {
    }

    /**
     * Test attribute "additional_info"
     */
    public function testPropertyAdditionalInfo()
    {
    }

    /**
     * Test attribute "gacid"
     */
    public function testPropertyGacid()
    {
    }

    /**
     * Test attribute "i_d2015"
     */
    public function testPropertyID2015()
    {
    }

    /**
     * Test attribute "registration_type_code"
     */
    public function testPropertyRegistrationTypeCode()
    {
    }

    /**
     * Test attribute "url_prof_test"
     */
    public function testPropertyUrlProfTest()
    {
    }

    /**
     * Test attribute "utm"
     */
    public function testPropertyUtm()
    {
    }

    /**
     * Test attribute "ut_mcontent"
     */
    public function testPropertyUtMcontent()
    {
    }

    /**
     * Test attribute "ut_mterm"
     */
    public function testPropertyUtMterm()
    {
    }

    /**
     * Test attribute "utm_source"
     */
    public function testPropertyUtmSource()
    {
    }

    /**
     * Test attribute "utm_medium"
     */
    public function testPropertyUtmMedium()
    {
    }

    /**
     * Test attribute "utm_campaign"
     */
    public function testPropertyUtmCampaign()
    {
    }

    /**
     * Test attribute "hot_lead"
     */
    public function testPropertyHotLead()
    {
    }

    /**
     * Test attribute "transaction_code"
     */
    public function testPropertyTransactionCode()
    {
    }
}
