<?php
/**
 * RegistrationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Maximum.CRM.WebApps.CommonIntegration
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * RegistrationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RegistrationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiRegistrationPost
     *
     * Создание регистрации в CRM.
     *
     */
    public function testApiRegistrationPost()
    {
    }

    /**
     * Test case for apiRegistrationRegistrationIdAgreementsGet
     *
     * Получение информации о договорах по CRM ID регистрации.
     *
     */
    public function testApiRegistrationRegistrationIdAgreementsGet()
    {
    }

    /**
     * Test case for apiRegistrationRegistrationIdGet
     *
     * Получение регистрации по CRM ID.
     *
     */
    public function testApiRegistrationRegistrationIdGet()
    {
    }

    /**
     * Test case for apiRegistrationRegistrationIdPut
     *
     * Обновление регистрации в CRM.
     *
     */
    public function testApiRegistrationRegistrationIdPut()
    {
    }

    /**
     * Test case for apiRegistrationTildaPost
     *
     * Создание регистрации в CRM для сервиса лендингов Tilda.
     *
     */
    public function testApiRegistrationTildaPost()
    {
    }
}
